# 1 Elasticsearch node, 1 Kibana instance - (v8.5.0)
version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.1
    container_name: kibana8.5.1
    environment:
      - elasticsearch.url=http://localhost:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    networks:
      - elastic-net

volumes:
  esnode-data:
    driver: local

networks:
  elastic-net:
