# 7 Elasticsearch node, 1 Kibana instance - (v8.5.0)

version: '3'
services:
  esnode1-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: esnode1-8.5.0
    environment:
      - node.name=esnode1-master
      - cluster.name=elastic-cluster
      - node.roles=master
      - cluster.initial_master_nodes=esnode1-master
      - discovery.seed_hosts=esnode2
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - path.repo=/usr/share/elasticsearch/backups
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esnode1-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic-net
  esnode2-data-content:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: esnode2-8.5.0
    environment:
      - node.name=esnode2-data_content
      - cluster.name=elastic-cluster
      - node.roles=data_content
      - cluster.initial_master_nodes=esnode1-master
      - discovery.seed_hosts=esnode1-master
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - path.repo=/usr/share/elasticsearch/backups
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esnode2-data:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
    networks:
      - elastic-net
  esnode3-hot-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: esnode3-8.5.0
    environment:
      - node.name=esnode3-hot-1
      - cluster.name=elastic-cluster
      - node.roles=data_hot
      - cluster.initial_master_nodes=esnode1-master
      - discovery.seed_hosts=esnode1-master
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - path.repo=/usr/share/elasticsearch/backups
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esnode3-data-hot:/usr/share/elasticsearch/data
    ports:
      - 9203:9200
    networks:
      - elastic-net    
  esnode4-hot-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: esnode4-8.5.0
    environment:
      - node.name=esnode4-hot-2
      - cluster.name=elastic-cluster
      - node.roles=data_hot
      - cluster.initial_master_nodes=esnode1-master
      - discovery.seed_hosts=esnode1-master
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - path.repo=/usr/share/elasticsearch/backups
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esnode4-data-hot:/usr/share/elasticsearch/data
    ports:
      - 9204:9200
    networks:
      - elastic-net   
  esnode5-cold:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: esnode5-8.5.0
    environment:
      - node.name=esnode5-cold
      - cluster.name=elastic-cluster
      - node.roles=data_cold
      - cluster.initial_master_nodes=esnode1-master
      - discovery.seed_hosts=esnode1-master
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - path.repo=/usr/share/elasticsearch/backups
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esnode5-co:/usr/share/elasticsearch/data
    ports:
      - 9205:9200
    networks:
      - elastic-net 
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: kibana8.5.0
    environment:
      - elasticsearch.url=http://elasticsearch:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    networks:
      - elastic-net
    links:
      - esnode1-master:elasticsearch

volumes:
  esnode1-data:
    driver: local
  esnode2-data:
    driver: local
  esnode3-data-hot:
    driver: local  
  esnode4-data-hot:
    driver: local
  esnode5-co:
    driver: local    
  
networks:
  elastic-net:
