# 2 Elasticsearch node, 1 Kibana instance - ElasticHQ (v8.5.0)
version: '3'
services:
  esnode1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: esnode1-8.5.0
    environment:
      - node.name=esnode1
      - cluster.name=elastic-cluster
      - cluster.initial_master_nodes=esnode1,esnode2
      - discovery.seed_hosts=esnode2
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - path.repo=/usr/share/elasticsearch/backups
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esnode1-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic-net
  esnode2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: esnode2-8.5.0
    environment:
      - node.name=esnode2
      - cluster.name=elastic-cluster
      - cluster.initial_master_nodes=esnode1,esnode2
      - discovery.seed_hosts=esnode1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - path.repo=/usr/share/elasticsearch/backups
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esnode2-data:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - elastic-net
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: kibana8.5.0
    environment:
      - elasticsearch.url=http://elasticsearch:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    networks:
      - elastic-net
    links:
      - esnode1:elasticsearch
  elastichq:
    image: elastichq/elasticsearch-hq
    container_name: elastichq
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:9200
      - HQ_DEBUG=False
    ports:
      - 5001:5000
    networks:
      - elastic-net
    links:
      - esnode1:elasticsearch

volumes:
  esnode1-data:
    driver: local
  esnode2-data:
    driver: local

networks:
  elastic-net:
