# 1 Elasticsearch node - (v7.13.1)
version: '3'
services:
  esnode:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: esnode7.13.1
    environment:
      - node.name=esnode
      - cluster.name=elastic-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esnode-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic-net

volumes:
  esnode-data:
    driver: local

networks:
  elastic-net:
